### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by edouard-lopez** [boris-graeff/labanane-app#3]
Il ya un équivalent de [React Native basé sur Vue.js: Weex](https://github.com/alibaba/weex).

**Comment by edouard-lopez** [comment]
La dernière version est responsive, je ferme.

**Comment by boris-graeff** [comment]
J'ai quand même des demandes pour avoir une appli mobile.
Mais j'ai pas le temps de me pencher sur ça pour l'instant.
