### ISSUE TITLE
Authentication is broken

### ISSUE THREAD

**Issue by edouard-lopez** [boris-graeff/labanane-app#6]
You should have a look at [JSON Web Token](https://jwt.io/)

**Comment by edouard-lopez** [comment]
Currently you can make a dirty fix by `encodeURIComponent()` before sending the request.

**Comment by boris-graeff** [comment]
Il faut que je creuse mais j'ai du mal à voir comment le mettre en application sur le projet pour l'instant, vu qu'il n'y a pas de notion de compte.

**Comment by boris-graeff** [comment]
J'ai splitté la request pour récupérer le contenu de la playlist et celle pour l'authentification.
Ca devrait régler le problème.
PR https://github.com/boris-graeff/labanane-app/pull/12
