### ISSUE TITLE
lost all playlist due to saving request error

### ISSUE THREAD

**Issue by edouard-lopez** [boris-graeff/labanane-app#8]
I created a playlist yesterday in a Chrome's private session, played song and all then close my browser. And when I came back to the app, the list of playlists displayed `0` next to my playlist so I opened it authenticate and got nothing :scream: 

```
www-widgetapi.js:119 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://labanane.no-ip.info').
g.C @ www-widgetapi.js:119
g.H @ www-widgetapi.js:116
…
xhr.js:175 PUT http://labanane.no-ip.info/services/playlists 422 (Unprocessable Entity)
(anonymous) @ xhr.js:175
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:50
actions.js:32 Playlist saving request failed
```

might be related to #8

**Comment by boris-graeff** [comment]
https://github.com/boris-graeff/labanane-app/pull/12

**Comment by boris-graeff** [comment]
Should by fixed by https://github.com/boris-graeff/labanane-app/pull/12
